defaults: &defaults
  adapter: mysql
  host: localhost

development:
  <<: *defaults
  database: people_system_development_mysql

test:
  <<: *defaults
  min_messages: warning #magic sauce
  database: people_system_test_mysql
